export const ActionTypes = {
  SET_ISREQUEST_STATE: 'SET_ISREQUEST_STATE',
  SET_LOADING_STATE: 'SET_LOADING_STATE',
  LOGIN_FORM_CHANGED: 'LOGIN_FORM_CHANGED',
  CLASSES_LIST_GET: 'CLASSES_LIST_GET',
  SELECTED_CLASS: 'SELECTED_CLASS',
  LOG_FORM_CHANGE: 'LOG_FORM_CHANGE',
  LOG_FORM_RESET: 'LOG_FORM_RESET',
  LOG_DATA_GET: 'LOG_DATA_GET',
  SET_CURRENT_WEEK_LOG: 'SET_CURRENT_WEEK_LOG',
  RESET_FORM_CHANGED: 'RESET_FORM_CHANGED',
  CLASS_DATA: 'CLASS_DATA'
};

export default ActionTypes;
